### ISSUE TITLE
Updating Log Spam

### ISSUE THREAD

**Issue by RealKolago** [malahx/QuickHide#3]
Testet with vanilla KSP and only

FerramAerospaceResearch
ModularFlightIntegrator
QuickHide

installed.

Log: https://www.dropbox.com/s/n5gjtti49m6qdvg/output_log3.zip?dl=0

**Comment by malahx** [comment]
Yes, I've also seen this, It's because FAR uses ApplicationLauncher.Ready on the GeometryPartModule to know if the Editor is loaded, I've corrected this this morning, an update will be soon here to don't hide the stock toolbar if there's no root part on the editor ...

https://github.com/ferram4/Ferram-Aerospace-Research/blob/a19e3c5170073ae1fe9331107b3ad6ed2b20f91c/FerramAerospaceResearch/FARPartGeometry/GeometryPartModule.cs#L105
